import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "./_components/TopBar";
import Footer from "./_components/Footer";
import TopBartwo from "./_components/TopBartwo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TribeSpacewebsite |The all-in-one best Community ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <TopBartwo/>
        {/* <Topbar/> */}
          <div>{children}</div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
